export enum SettingActionTypes {
  TOGGLE_COLOR_BLIND = 'TOGGLE_COLOR_BLIND',
  TOGGLE_TIME_CHALLENGE = 'TOGGLE_TIME_CHALLENGE',
  TOGGLE_REDUCED_MOTION = 'TOGGLE_REDUCED_MOTION',
  TOGGLE_LETTER_HELPER = 'TOGGLE_LETTER_HELPER',
  TOGGLE_DARK_THEME = 'TOGGLE_DARK_THEME',
  SAVE = 'SAVE',
  LOAD = 'LOAD',
}
